/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#faf8ff",
        "surface-tint": "#0053db",
        "primary": "#004ac6",
        "inverse-surface": "#283044",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary": "#505f76",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-container": "#54647a",
        "on-primary": "#ffffff",
        "on-background": "#131b2e",
        "tertiary-fixed": "#ffddb8",
        "surface-variant": "#dae2fd",
        "surface-container-low": "#f2f3ff",
        "tertiary": "#784b00",
        "secondary-fixed-dim": "#b7c8e1",
        "error-container": "#ffdad6",
        "surface-dim": "#d2d9f4",
        "on-surface": "#131b2e",
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#ffeedd",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed-dim": "#ffb95f",
        "tertiary-container": "#996100",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-primary": "#b4c5ff",
        "surface": "#faf8ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#434655",
        "background": "#faf8ff",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-highest": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "primary-container": "#2563eb",
        "surface-container": "#eaedff",
        "primary-fixed-dim": "#b4c5ff",
        "secondary-container": "#d0e1fb",
        "inverse-on-surface": "#eef0ff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "on-error-container": "#93000a",
        "outline": "#737686",
        "on-tertiary-fixed": "#2a1700"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "20px",
        "container-max": "1280px",
        "xs": "4px",
        "md": "16px",
        "lg": "24px",
        "base": "4px",
        "xl": "40px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "30px", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "button": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "headline-lg": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
